name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build EXE
      run: GOOS=windows GOARCH=amd64 go build -o sniper.exe main.go

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: roblox-sniper-exe
        path: sniper.exe
